version: '3'

services:
  vt:
    build: ./ # Specify the directory of the Dockerfile
    ports:
      - "3000:3000" # Specify ports for forwarding
    links:
      - database # Link this service to the database service
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: mongo:latest
